### PR TITLE
fix banking plugin

### PR DESCRIPTION
**Pull request by hallowatcher**
After the filestore update (I think), some of the options changed for banking.
I also refactored duplicate code for it to look a bit nicer

Also fixed the issue of the banking interface not opening when trying to accessing through dialogue

### CODE REVIEW

**Comment by Promises** [comment]
I wrote some bots to test this last time, I'll see if I can find them.

**Comment by SchauweM** [comment]
@Promises  do you want to include the bots in the PR before we approve it or?

**Comment by Promises** [comment]
@SchauweM no they are just command i added to the java client to try to dupe and break the bank, ill run it after work if i still have it

**Comment by hallowatcher** [comment]
ready for review/merge

**Review by Promises — APPROVED** [review]
looks alright to me :)

**Pull request merged**
