### PR TITLE
Optimise container updating

### PR DESCRIPTION
**Pull request by Hc747**
- TODO: reasonable default byte buffer allocation size.
- TODO: further reduce packet payload size.
Reduces container update payload size by a factor of 16.

### CODE REVIEW

**Comment by Hc747** [comment]
@Promises @TheBlackParade 
Requires a client sided modification.
Can be further optimised.

**Comment by Promises** [comment]
@Hc747 do you need me to do the client side modifications?

**Comment by Hc747** [comment]
I’m happy to; can you link the client repo & appropriate place to handle the modification?

**Comment by Promises** [comment]
https://github.com/Promises/refactored-client-435

**Comment by TheBlackParade** [comment]
The outgoing packet buffer size can be reduced by pulling the packet sizes from the client and using those when creating new packets - search the array for the packet ID and use that size to create the buffer. That was the plan, anyways.

**Comment by Hc747** [comment]
@Promises @TheBlackParade Ready for merging.

**Pull request merged**
